[workspace]
authors = ["Nicolas <nicolas@ardisoft.com>"]
channels = ["conda-forge"]
name = "MyShittyNoteAnalyser"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=1.23,<3"
pyqt6 = ">=6.11.0,<7"
aubio = "*"
portaudio = ">=19.7.0,<20"

[pypi-dependencies]
sounddevice = ">=0.5.5, <0.6"
